# Generated by Django 3.2.8 on 2022-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=10)),
                ('simple_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('eng_id', models.CharField(max_length=10)),
            ],
        ),
    ]
