# Generated by Django 3.2.8 on 2022-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_active_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
