# Generated by Django 3.2.8 on 2022-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_member_last_active_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stock_code',
            field=models.FileField(default='txt/member_stock/default_member_stock.txt', upload_to='txt/member_stock/'),
        ),
    ]
