# Generated by Django 3.2.8 on 2022-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_member_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(default='http://175.178.119.52/static/image/test.png', upload_to='http://175.178.119.52/static/image/member_photo/'),
        ),
    ]
