# Generated by Django 3.2.8 on 2022-04-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_alter_member_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='code',
            new_name='family_password',
        ),
    ]
